//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jospin.DeepSound.Modules.Converter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jospin.DeepSound.Modules.Converter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Convert {
            get {
                object obj = ResourceManager.GetObject("Convert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeepSound {
            get {
                object obj = ResourceManager.GetObject("DeepSound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio files ({0})|{1}.
        /// </summary>
        internal static string T001 {
            get {
                return ResourceManager.GetString("T001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string T002 {
            get {
                return ResourceManager.GetString("T002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir.
        /// </summary>
        internal static string T003 {
            get {
                return ResourceManager.GetString("T003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (MB).
        /// </summary>
        internal static string T004 {
            get {
                return ResourceManager.GetString("T004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string T005 {
            get {
                return ResourceManager.GetString("T005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert {0} files to {1}?.
        /// </summary>
        internal static string T006 {
            get {
                return ResourceManager.GetString("T006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert was aborted by user..
        /// </summary>
        internal static string T007 {
            get {
                return ResourceManager.GetString("T007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string T008 {
            get {
                return ResourceManager.GetString("T008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string T009 {
            get {
                return ResourceManager.GetString("T009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Converter.
        /// </summary>
        internal static string T010 {
            get {
                return ResourceManager.GetString("T010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Converter (F6).
        /// </summary>
        internal static string T011 {
            get {
                return ResourceManager.GetString("T011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string T012 {
            get {
                return ResourceManager.GetString("T012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert is completed. Duration: {0}.
        /// </summary>
        internal static string T013 {
            get {
                return ResourceManager.GetString("T013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files.
        /// </summary>
        internal static string T014 {
            get {
                return ResourceManager.GetString("T014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files (F2).
        /// </summary>
        internal static string T015 {
            get {
                return ResourceManager.GetString("T015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string T016 {
            get {
                return ResourceManager.GetString("T016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert (F3).
        /// </summary>
        internal static string T017 {
            get {
                return ResourceManager.GetString("T017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format.
        /// </summary>
        internal static string T018 {
            get {
                return ResourceManager.GetString("T018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from list.
        /// </summary>
        internal static string T019 {
            get {
                return ResourceManager.GetString("T019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory:.
        /// </summary>
        internal static string T020 {
            get {
                return ResourceManager.GetString("T020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel (Esc).
        /// </summary>
        internal static string T021 {
            get {
                return ResourceManager.GetString("T021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripping CD...
        /// </summary>
        internal static string T022 {
            get {
                return ResourceManager.GetString("T022", resourceCulture);
            }
        }
    }
}
